name: Main Pipeline

on:
  workflow_dispatch:
    inputs:
      exit_code:
        required: true
        default: "0"
        description: The exit code when running the pipeline

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Plan TF
    continue-on-error: true
    steps:
      - name: Run with specific exit code
        id: plan_tf
        run: |
          echo "Planning things"
          (exit $EXIT_CODE)
          exit_code=$?
          if [ "$exit_code" -eq 0 ]; then
            echo "No changes."
            exit 0
          elif [ "$exit_code" -eq 2 ]; then
            echo "Changes present."
            exit 0
          else
            echo "Terraform error."
            exit 1
          fi
          echo "tfplan_exit=$exit_code" >> $GITHUB_OUTPUT
        env:
          EXIT_CODE: ${{ github.event.inputs.exit_code }}
    outputs:
      exit_code: ${{ steps.plan_tf.outputs.tfplan_exit }}

  deploy:
    environment:
      name: staging
    runs-on: ubuntu-latest
    needs: plan
    name: Deploy TF
    if: needs.plan.outputs.exit_code == '3'
    steps:
      - name: Deploy TF
        id: deploy_tf
        run: |
          echo "Deploying things"

  other:
    runs-on: ubuntu-latest
    needs: [plan, deploy]
    name: Do other things
    if: always() && needs.plan.result == 'success' && (needs.deploy.result == 'success' || needs.deploy.result == 'skipped')
    steps:
      - name: Deploy TF
        id: deploy_tf
        run: |
          echo "Deploying things"
